apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: recruiter-cms
  labels:
    app: recruiter-cms
spec:
  selector:
    app: recruiter-cms
  ports:
    - port: 3000
      name: recruiter-cms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: recruiter-cms
  labels:
    app: recruiter-cms
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: recruiter-cms
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: recruiter-cms
    spec:
      containers:
        - name: recruiter-cms
          image: notekunn/recruiter-cms:1.15.0 # {"$imagepolicy": "flux-system:recruiter-cms"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: recruiter-cms
          env:
            - name: SERVICE_HOST
              value: '0.0.0.0'
            - name: SERVICE_PORT
              value: '3000'
            - name: GOOGLEMAP_API_KEY
              value: 'AIzaSyDm_uG7jcclLM5QXjScNF8mkYrIhe3IEzw'
            - name: JWT_SECRET_KEY
              value: 'cuongdeptrai'
            - name: JWT_EXPIRATION_TIME
              value: '7d'
            - name: DB_HOST
              value: 'db-postgresql-nyc1-59855-do-user-6507062-0.b.db.ondigitalocean.com'
            - name: DB_PORT
              value: '25060'
            - name: DB_USERNAME
              value: 'doadmin'
            - name: DB_PASSWORD
              value: 'AVNS_vAlPbwQWY4lohBYDjpU'
            - name: DB_DATABASE
              value: 'defaultdb'
            - name: DB_SSL
              value: 'true'
            - name: UID_SERVICE_HOST
              value: 'https://cvnl.me/uuid/v1'
            - name: ELASTICSEARCH_URL
              value: 'https://elastic.kma-news.tech/'
          resources:
            requests:
              memory: '896Mi'
              cpu: '700m'
            limits:
              memory: '1Gi'
              cpu: '800m'
