name: 💿

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Version of service

jobs:
  docker:
    name: Build image 💿
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@notekunn'
        env:
          NPM_AUTH_TOKEN: ${{ secrets.PAT }}
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
        if: ${{ github.event_name == 'release' }}
        with:
          tagRegex: '@(?<package>.*)@(?<version>.*)'
      - run: echo "RELEASE_VERSION=${{ steps.tagName.outputs.version }}" >> $GITHUB_ENV
        if: ${{ github.event_name == 'release' }}
        name: Set env
      - name: Set env
        run: echo "RELEASE_VERSION=${{inputs.version}}" >> $GITHUB_ENV
        if: ${{ github.event_name == 'workflow_dispatch'}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: notekunn/recruiter-cms:${{ env.RELEASE_VERSION }}
          secrets: |
            "token=${{ secrets.PAT }}"
          secret-files: |
            "npmrc=${{ env.NPM_CONFIG_USERCONFIG }}"
