name: 💿

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Version of service

jobs:
  docker:
    name: Build image 💿
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }} || \
      ${{ github.event_name == 'release' && startsWith(github.ref, '222@vnact/recruiter-cms')}}
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{github.ref}}
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/@vnact/recruiter-cms@/*/}" >> $GITHUB_ENV
        if: ${{ github.event_name == 'release' }}
      - name: Set env
        run: echo "RELEASE_VERSION=${{inputs.version}}" >> $GITHUB_ENV
        if: ${{ github.event_name == 'workflow_dispatch'}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: notekunn/recruiter:${{ env.RELEASE_VERSION }}
          secrets: |
            "token=${{ secrets.GITHUB_TOKEN  }}"
          secret-files: |
            "npmrc=${{ env.NPM_CONFIG_USERCONFIG }}"
