name: 💿

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Version of service

jobs:
  docker:
    name: Build image 💿
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{github.ref}}
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
        if: ${{ github.event_name == 'release' }}
        with:
          tagRegex: '@(?<package>.*)@(?<version>.*)'
      - name: Set env
        run: echo "GIT_TAG_NAME=${{inputs.version}}" >> $GITHUB_ENV
        if: ${{ github.event_name == 'workflow_dispatch'}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: notekunn/recruiter:${{ env.GIT_TAG_NAME }}
          secrets: |
            "token=${{ secrets.GITHUB_TOKEN  }}"
          secret-files: |
            "npmrc=${{ env.NPM_CONFIG_USERCONFIG }}"
